### ISSUE TITLE
halogenizing

### ISSUE THREAD

**Issue by jamesthompson** [themoritz/purescript-flatpickr#1]
@themoritz Any plans to Halogenize this? If not, I might have a go if you wouldn't mind...

Thank you very much for building this library.

**Comment by themoritz** [comment]
I've actually already built a halogen component around it in a private project. Since you are interested, it might be a good idea to make a library out of it. It doesn't wrap all of the flatpickr functionality, but it would be a good starting point.

**Comment by jamesthompson** [comment]
That's awesome. I'm definitely interested in using it. If there's any work that needs doing to bring it to full spec that I can help with just let me know.

**Comment by themoritz** [comment]
Ok, I've put the code here: https://github.com/themoritz/purescript-flatpickr-halogen

Please feel free to add any functionality from the spec that you might need and make PRs.
